/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-04-15 07:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.atlassian.config.util.BootstrapUtils;
import com.atlassian.confluence.cluster.ClusterInformation;
import com.atlassian.confluence.cluster.ClusterManager;
import com.atlassian.confluence.jmx.RequestMetrics;
import com.atlassian.confluence.plugin.persistence.PluginData;
import com.atlassian.confluence.plugin.persistence.PluginDataDao;
import com.atlassian.confluence.status.SystemErrorInformationLogger;
import com.atlassian.confluence.status.service.SystemInformationService;
import com.atlassian.confluence.status.service.systeminfo.ConfluenceInfo;
import com.atlassian.confluence.status.service.systeminfo.DatabaseInfo;
import com.atlassian.confluence.status.service.systeminfo.MemoryInfo;
import com.atlassian.confluence.util.GeneralUtil;
import com.atlassian.confluence.util.I18NSupport;
import com.atlassian.confluence.util.PatternLayoutWithStackTrace;
import com.atlassian.core.logging.DatedLoggingEvent;
import com.atlassian.core.logging.ThreadLocalErrorCollection;
import com.atlassian.plugin.Plugin;
import com.atlassian.plugin.PluginInformation;
import com.atlassian.seraph.auth.DefaultAuthenticator;
import com.atlassian.spring.container.ContainerManager;
import org.apache.commons.lang.StringUtils;
import org.apache.log4j.spi.LoggingEvent;
import org.apache.velocity.exception.MethodInvocationException;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.StringReader;
import java.lang.reflect.InvocationTargetException;
import java.security.Principal;
import java.text.DateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

public final class _500page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 String context = request.getContextPath(); 
      out.write('\n');
 try { 
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <title>Oops - an error has occurred</title>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print( context );
      out.write("/includes/js/cookieUtils.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"PageContent\">\n");
      out.write("<h1>\n");
      out.write("    <a href=\"");
      out.print( context );
      out.write("/\">\n");
      out.write("            <img src=\"");
      out.print( context );
      out.write("/images/logo/confluence_48_white.png\" alt=\"logo\" title=\"Confluence\">\n");
      out.write("    </a>\n");
      out.write("    System Error\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("<div id=\"sysErrPanel\" class=\"panel\">\n");
      out.write("    <p>\n");
      out.write("        A system error has occurred &mdash; our apologies!\n");
      out.write("    </p>\n");
      out.write("    <p>\n");
      out.write("        For immediate troubleshooting, consult our <strong><a href=\"");
      out.print( I18NSupport.getText("url.confluence.knowledge.base") );
      out.write("\">knowledge base</a></strong> for a solution.\n");
      out.write("    </p>\n");
      out.write("    <p>\n");
      out.write("        If you would like to receive support from Atlassian's support team, ask your\n");
      out.write("        <strong><a href=\"");
      out.print( context );
      out.write("/contactadministrators.action\">Confluence administrator</a></strong> to create a support issue on <a href=\"");
      out.print( I18NSupport.getText("url.support") );
      out.write("\">Atlassian's support system</a> with the following information:\n");
      out.write("    </p>\n");
      out.write("    <ol>\n");
      out.write("        <li>a description of your problem and what you were doing at the time it occurred</li>\n");
      out.write("        <li>a copy of the error and system information found below</li>\n");
      out.write("        <li>a copy of the application logs (if possible).</li>\n");
      out.write("    </ol>\n");
      out.write("    <p>\n");
      out.write("        Your Confluence administrator can use the\n");
      out.write("        <strong><a href=\"");
      out.print( context );
      out.write("/admin/raisesupportrequest.action\">support request form</a></strong>\n");
      out.write("        to create a support ticket which will include this information.\n");
      out.write("    </p>\n");
      out.write("    <p>\n");
      out.write("        We will respond as promptly as possible.<br>\n");
      out.write("        Thank you!\n");
      out.write("    </p>\n");
      out.write("    <p>\n");
      out.write("        <a href=\"");
      out.print( context );
      out.write("/\"><strong>Return to site homepage&hellip;</strong></a>\n");
      out.write("    </p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("        ");

        	UUID uniqueID = UUID.randomUUID();  // enable an easy mapping between this page and the error log.
        	SystemErrorInformationLogger logAction = new SystemErrorInformationLogger(uniqueID, pageContext.getServletContext(), request);
            logAction.writeToLog(false);
            RequestMetrics.incrementErrorCount();


            SystemInformationService sysInfoService = null;
            PluginDataDao pluginDataDao = null;
            Throwable sysInfoRetrievalFailure = null;
            try
            {
                sysInfoService = ((SystemInformationService) ContainerManager.getInstance().getContainerContext().getComponent("systemInformationService"));
                pluginDataDao = (PluginDataDao) ContainerManager.getInstance().getContainerContext().getComponent("pluginDataDao");
            }
            catch (Throwable t)
            {
                sysInfoRetrievalFailure = t;
            }           
            
            // These variables are kept at a high scope to simplify the complexity of following scope in a
        	// JSP like this one.
        	//
            // sysInfoService being null will be used as a the check as to whether we should expect
            // non-null in any of these variables.
        	Map sysinfo = null;
        	MemoryInfo memoryInfo = null;
        	DatabaseInfo dbInfo = null;
        	ConfluenceInfo confluenceInfo = null;
        	boolean isOrion = false;

        	if (sysInfoService != null)
        	{
	        	confluenceInfo = sysInfoService.getConfluenceInfo();
	        	memoryInfo = sysInfoService.getMemoryInfo();
	        	dbInfo = sysInfoService.getSafeDatabaseInfo();
                sysinfo = GeneralUtil.convertBeanToMap(sysInfoService.getSystemProperties());

	    		isOrion = "Orion".equals(sysinfo.get("appServer"));
        	}
        	else
        	{
        		out.println("The SystemInformationService could not be retrieved from the container.");
        		out.println("Therefore very limited information is available in this error report. <br>");
                if (sysInfoRetrievalFailure != null)
                {
      out.write("The SystemInformationService could not be retrieved due to the following error:\n");
      out.write("                   ");
      out.print( GeneralUtil.htmlEncode(String.valueOf(sysInfoRetrievalFailure)) );
      out.write("<br>");
                 
                }
            }
        
      out.write("\n");
      out.write("\n");
      out.write("    ");

        String uri = (String)request.getAttribute("javax.servlet.error.request_uri");
        if(uri != null && uri.contains("editpage"))
        {
            String editDraft = context + "/pages/editpage.action?useDraft=true&pageId=" + GeneralUtil.htmlEncode(request.getParameter("pageId"));
            
      out.write("\n");
      out.write("            <div class=\"panel warning\">\n");
      out.write("                <img id=\"draftNote\" alt=\"\" src=\"");
      out.print( context );
      out.write("/images/icons/emoticons/warning.png\">\n");
      out.write("                You can <a href=\"");
      out.print( editDraft );
      out.write("\">resume editing</a> the most recently saved draft of your page.\n");
      out.write("            </div>\n");
      out.write("        ");
 
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    <h3>Cause</h3>\n");
      out.write("    ");

        String ex = (String) request.getAttribute("javax.servlet.error.message");
        if (isOrion)
        {
            //get the first line of the error message for the "cause:"
            String line = (ex == null) ? "No exception" : new BufferedReader(new StringReader(ex)).readLine();
        
      out.write("\n");
      out.write("        <p>");
      out.print( GeneralUtil.htmlEncode(line) );
      out.write("</p>\n");
      out.write("        ");

        }
        else
        {
            Throwable throwable = exception;
            String causedBy = "";
            while (throwable != null)
            {
                String at = throwable.getStackTrace().length > 0 ? throwable.getStackTrace()[0].toString() : "Unknown location";
            
      out.write("\n");
      out.write("            <p>\n");
      out.write("                ");
      out.print( causedBy );
      out.print( GeneralUtil.htmlEncode(String.valueOf(throwable)) );
      out.write("<br>\n");
      out.write("                &nbsp;&nbsp;&nbsp;&nbsp;at ");
      out.print( GeneralUtil.htmlEncode(at) );
      out.write("\n");
      out.write("            </p>\n");
      out.write("            ");

                causedBy = "caused by: ";
                if (throwable instanceof InvocationTargetException)
                {
                    throwable = ((InvocationTargetException)throwable).getTargetException();
                }
                else if (throwable instanceof MethodInvocationException)
                {
                    throwable = ((MethodInvocationException)throwable).getWrappedThrowable();
                }
                else if (throwable instanceof ServletException)
                {
                    throwable = ((ServletException)throwable).getRootCause();
                }
                else
                {
                    throwable = throwable.getCause();
                }
            }
        }
        
      out.write("\n");
      out.write("\n");
      out.write("        <h4>Stack Trace:<span class=\"switch\" id=\"stacktrace-switch\" onclick=\"toggle('stacktrace')\">[hide]</span></h4>\n");
      out.write("\n");
      out.write("        ");
 if (isOrion) { 
      out.write("\n");
      out.write("        <pre id=\"stacktrace\">");
      out.print( GeneralUtil.htmlEncode(ex) );
      out.write("</pre>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <pre id=\"stacktrace\">");

            StringBuffer sb = new StringBuffer();
            PatternLayoutWithStackTrace.appendStackTrace(sb, exception);
            out.print(GeneralUtil.htmlEncode(sb.toString()));
        
      out.write("\n");
      out.write("        </pre>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <h3>Referer URL</h3>\n");
      out.write("        <p>");
      out.print( request.getHeader("Referer") != null ? GeneralUtil.htmlEncode(request.getHeader("Referer")) : "Unknown" );
      out.write("</p>\n");
      out.write("\n");
      out.write("        ");
 if ((sysInfoService != null) && sysInfoService.isShowInfoOn500()) {
      out.write("\n");
      out.write("            <h3>Confluence Application Information</h3>\n");
      out.write("            <h4>Build Information</h4>\n");
      out.write("            <p>\n");
      out.write("            ");

                if (confluenceInfo != null) {

                    Map buildstats = GeneralUtil.convertBeanToMap(confluenceInfo);

                    // remove the properties that we don't want to display in the maps
                    buildstats.remove("enabledPlugins");
                    buildstats.remove("startTime");
                    buildstats.remove("globalSettings");


                    for (Iterator it = buildstats.entrySet().iterator(); it.hasNext();)
                    {
                        Map.Entry entry = (Map.Entry) it.next();
            
      out.write("\n");
      out.write("                    ");
      out.print( entry.getKey() );
      out.write(':');
      out.write(' ');
      out.print( entry.getValue() );
      out.write("<br>\n");
      out.write("            ");
      }
                } else { 
      out.write("\n");
      out.write("                No build information available.\n");
      out.write("            ");
  } 
      out.write("\n");
      out.write("                Unique ID: ");
      out.print( uniqueID.toString());
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <h4>Server information</h4>\n");
      out.write("            <p>\n");
      out.write("                Application Server: ");
      out.print( application.getServerInfo() );
      out.write("<br>\n");
      out.write("                Servlet Version: ");
      out.print( application.getMajorVersion() );
      out.write('.');
      out.print( application.getMinorVersion() );
      out.write("<br>\n");
      out.write("                ");
 if (dbInfo != null) { 
      out.write("\n");
      out.write("                    Database Dialect: ");
      out.print( dbInfo.getDialect() );
      out.write("<br>\n");
      out.write("                    Database Driver Name: ");
      out.print( dbInfo.getDriverName() );
      out.write("<br>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    No database information available.\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <h4>Memory Information</h4>\n");
      out.write("            <p>\n");
      out.write("            ");
 if (memoryInfo != null) { 
      out.write("\n");
      out.write("                Maximum Heap: ");
      out.print( memoryInfo.getMaxHeap().megabytes() );
      out.write(" MB<br>\n");
      out.write("                Allocated Heap: ");
      out.print( memoryInfo.getAllocatedHeap().megabytes() );
      out.write(" MB<br>\n");
      out.write("                Used Memory: ");
      out.print( memoryInfo.getUsedHeap().megabytes() );
      out.write(" MB<br>\n");
      out.write("                Unused Allocated Memory: ");
      out.print( memoryInfo.getFreeAllocatedHeap().megabytes() );
      out.write(" MB<br>\n");
      out.write("                Available Memory: ");
      out.print( memoryInfo.getAvailableHeap().megabytes() );
      out.write(" MB<br>\n");
      out.write("                <br>\n");
      out.write("                Maximum Permgen: ");
      out.print( memoryInfo.getMaxPermGen().megabytes());
      out.write(" MB<br>\n");
      out.write("                Used Permgen: ");
      out.print( memoryInfo.getUsedPermGen().megabytes());
      out.write(" MB<br>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                No memory information available.\n");
      out.write("            ");
	} 
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <h4>System Information</h4>\n");
      out.write("            <p>\n");
      out.write("            ");
  if (sysinfo != null) {
                    for (Iterator it = sysinfo.entrySet().iterator(); it.hasNext();)
                    {
                        Map.Entry entry = (Map.Entry) it.next();
                    
      out.write("\n");
      out.write("                        ");
      out.print( entry.getKey() );
      out.write(':');
      out.write(' ');
      out.print( entry.getValue() );
      out.write("<br>\n");
      out.write("            ");
      }
                } else { 
      out.write("\n");
      out.write("                No system information available.\n");
      out.write("            ");
  } 
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            ");
 if (BootstrapUtils.getBootstrapManager().getHibernateConfig().isHibernateSetup()) {
      out.write("\n");
      out.write("                <h4>Cluster Information</h4>\n");
      out.write("                ");
 try { 
      out.write("\n");
      out.write("                    ");
 ClusterManager clusterManager = (ClusterManager) ContainerManager.getComponent("clusterManager"); 
      out.write("\n");
      out.write("                    ");
 if (!clusterManager.isClustered()) { 
      out.write("\n");
      out.write("                            <p>Not clustered.</p>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        ");
 ClusterInformation clusterInformation = clusterManager.getClusterInformation(); 
      out.write("\n");
      out.write("                        <p>\n");
      out.write("                            Name: ");
      out.print( GeneralUtil.htmlEncode(clusterInformation.getName()));
      out.write(" <br>\n");
      out.write("                            Description: ");
      out.print( GeneralUtil.htmlEncode(clusterInformation.getDescription()));
      out.write(" <br>\n");
      out.write("                            Members:<br>\n");
      out.write("                            ");

                                for (Iterator it = clusterInformation.getMembers().iterator(); it.hasNext();)
                                {
                            
      out.write("\n");
      out.write("                                    - ");
      out.print( GeneralUtil.htmlEncode(String.valueOf(it.next())) );
      out.write("<br>\n");
      out.write("                            ");
  } 
      out.write("\n");
      out.write("                        </p>\n");
      out.write("                   ");
 } 
      out.write("\n");
      out.write("                ");
 } catch (Throwable t) { 
      out.write("\n");
      out.write("                    <p>Error reporting cluster information: ");
      out.print( GeneralUtil.htmlEncode(t.toString()) );
      out.write("</p>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <h3>Plugins</h3>\n");
      out.write("            <ul class=\"plugins\">\n");
      out.write("            ");
  if (confluenceInfo != null) {
                    DateFormat format = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.US);
                    try
                    {
                        for (Iterator it = confluenceInfo.getEnabledPlugins().iterator(); it.hasNext();)
                        {
                            Plugin plugin = (Plugin) it.next();
                            PluginInformation pluginInfo = plugin.getPluginInformation();
                            String pluginName = plugin.getName();
                            String pluginKey = plugin.getKey();
                            String pluginVersion = pluginInfo == null ? "N/A" : pluginInfo.getVersion();
                            if (pluginVersion == null) // sometimes the version isn't defined by the plugin
                                pluginVersion = "N/A";

                            String lastModifiedStr = pluginDataDao == null ? "unknown" : "bundled";
                            if (pluginDataDao != null && pluginDataDao.pluginDataExists(pluginKey))
                            {
                                PluginData pluginData = pluginDataDao.getPluginData(pluginKey);
                                Date lastModified = pluginData != null ? pluginData.getLastModificationDate() : null;
                                if (lastModified != null)
                                {
                                    lastModifiedStr = format.format(lastModified);
                                }
                            }
            
      out.write("\n");
      out.write("                            <li>");
      out.print( GeneralUtil.htmlEncode(pluginName) );
      out.write(' ');
      out.write('(');
      out.print( GeneralUtil.htmlEncode(pluginKey) );
      out.write(", Version: ");
      out.print( pluginVersion );
      out.write(", Installed: ");
      out.print( lastModifiedStr );
      out.write(") </li>\n");
      out.write("            ");
          }
                    } catch (Exception e) { 
      out.write("\n");
      out.write("                        <li>Error retrieving plugin information: ");
      out.print( GeneralUtil.htmlEncode(e.toString()) );
      out.write("</li>\n");
      out.write("            ");
      }
                } else { 
      out.write("\n");
      out.write("                    <li>No plugin information available.</li>\n");
      out.write("            ");
  } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h3>Request</h3>\n");
      out.write("            ");

                try {
            
      out.write("\n");
      out.write("            <h4>Information</h4>\n");
      out.write("            <dl>\n");
      out.write("                <dt>URL</dt><dd>");
      out.print( GeneralUtil.htmlEncode(request.getRequestURL().toString()) );
      out.write("\n");
      out.write("                <dt>URI</dt><dd>");
      out.print( GeneralUtil.htmlEncode(request.getRequestURI()) );
      out.write("\n");
      out.write("                <dt>Context Path</dt><dd>");
      out.print( request.getContextPath() );
      out.write("</dd>\n");
      out.write("                <dt>Servlet Path</dt><dd>");
      out.print( request.getServletPath() );
      out.write("</dd>\n");
      out.write("                ");
 if (StringUtils.isNotBlank(request.getPathInfo())) { 
      out.write("\n");
      out.write("                    <dt>Path Info</dt><dd>");
      out.print( GeneralUtil.htmlEncode(request.getPathInfo()) );
      out.write("</dd>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                ");
 if (StringUtils.isNotBlank(request.getQueryString())) { 
      out.write("\n");
      out.write("                <dt>Query String</dt><dd>");
      out.print( GeneralUtil.htmlEncode(request.getQueryString()) );
      out.write("</dd>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </dl>\n");
      out.write("            <h4>Headers (Limited subset)</h4>\n");
      out.write("            <dl>\n");
      out.write("            ");

                String[] headers = new String[]{"host", "x-forwarded-for", "user-agent", "keep-alive",
                    "connection", "cache-control", "if-modified-since", "if-none-match"};
                for (int i = 0; i < headers.length; i++)
                {
                    String name = headers[i];
                    Enumeration headerValues = request.getHeaders(name);
                    if (headerValues == null || !headerValues.hasMoreElements()) continue;
            
      out.write("\n");
      out.write("                    <dt>");
      out.print( GeneralUtil.htmlEncode(name) );
      out.write("</dt>\n");
      out.write("            ");

                    while (headerValues.hasMoreElements())
                    {
            
      out.write("\n");
      out.write("                    <dd>");
      out.print( GeneralUtil.htmlEncode(String.valueOf(headerValues.nextElement())));
      out.write("</dd>\n");
      out.write("            ");

                    }
                }
            
      out.write("\n");
      out.write("            </dl>\n");
      out.write("            <h4>Attributes</h4>\n");
      out.write("            <dl>\n");
      out.write("            ");

                for (Enumeration attributeNames = request.getAttributeNames(); attributeNames.hasMoreElements();)
                {
                    String name = String.valueOf(attributeNames.nextElement());
                
      out.write("\n");
      out.write("                    <dt>");
      out.print( GeneralUtil.htmlEncode(name) );
      out.write("</dt>\n");
      out.write("                    <dd>");
      out.print( GeneralUtil.htmlEncode(String.valueOf(request.getAttribute(name))));
      out.write("</dd>\n");
      out.write("                ");

                }
            
      out.write("\n");
      out.write("            </dl>\n");
      out.write("            <h4>Parameters (Limited subset)</h4>\n");
      out.write("            <dl>\n");
      out.write("            ");

                for (Enumeration parameterNames = request.getParameterNames(); parameterNames.hasMoreElements();)
                {
                    String name = String.valueOf(parameterNames.nextElement());
                    if (name.contains("pass")) continue;
                
      out.write("\n");
      out.write("                <dt>");
      out.print( GeneralUtil.htmlEncode(name) );
      out.write("</dt>\n");
      out.write("                ");

                    String[] parameterValues = request.getParameterValues(name);
                    for (int i = 0; i < parameterValues.length; i++)
                    {
                        
      out.write("\n");
      out.write("                        <dd>");
      out.print( GeneralUtil.htmlEncode(parameterValues[i]) );
      out.write("</dd>\n");
      out.write("                        ");

                    }
                }
            
      out.write("\n");
      out.write("            </dl>\n");
      out.write("            <h3>Confluence User</h3>\n");
      out.write("            ");

                Object loggedInValue = session.getAttribute(DefaultAuthenticator.LOGGED_IN_KEY);
                String username = null;
                if ((loggedInValue != null) && (loggedInValue instanceof Principal))
                {
                    username = ((Principal)loggedInValue).getName();
                }
                else
                {
                    username = "unknown";
                }
            
      out.write("\n");
      out.write("            <p>\n");
      out.write("                ");
      out.print( username );
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            ");

                }
                catch (Throwable t)
                {
                    out.println("Error rendering logging information - uh oh.");
                    t.printStackTrace(new PrintWriter(out));
                }
            
      out.write("\n");
      out.write("\n");
      out.write("        ");
  List events = ThreadLocalErrorCollection.getList();
            if (events != null && !events.isEmpty()) { 
      out.write("\n");
      out.write("            <h3>Logging:</h3>\n");
      out.write("            ");
  try { 
      out.write("\n");
      out.write("                <p>");
      out.print( events.size() );
      out.write(" log statements generated by this request:</p>\n");
      out.write("                ");

                    for (Iterator it = events.iterator(); it.hasNext();)
                    {
                        Object event = it.next();
                        if (event instanceof DatedLoggingEvent) {
                            DatedLoggingEvent dle = (DatedLoggingEvent) event;
                            LoggingEvent loggingEvent = dle.getEvent();
                            Date date = dle.getDate();
                    
      out.write("\n");
      out.write("                        <div class=\"logStatement\">\n");
      out.write("                            <em class=\"bad\">[");
      out.print( GeneralUtil.htmlEncode(loggingEvent.getLevel().toString()) );
      out.write("]</em>\n");
      out.write("                            ");
      out.print( GeneralUtil.htmlEncode(date.toString()) );
      out.write("\n");
      out.write("                            [");
      out.print( GeneralUtil.htmlEncode(loggingEvent.getLoggerName()) );
      out.write("]\n");
      out.write("                            ");
      out.print( GeneralUtil.htmlEncode(loggingEvent.getRenderedMessage()) );
      out.write("\n");
      out.write("                            <br>\n");
      out.write("                            ");
 if (loggingEvent.getThrowableInformation() != null) { 
      out.write("\n");
      out.write("                                <div class=\"logThrowable\">\n");
      out.write("                                    <strong>Throwable:</strong><br>\n");
      out.write("                                    ");

                                        for (int i = 0; i < loggingEvent.getThrowableStrRep().length && i < 20; i++)
                                        {
                                            String s = loggingEvent.getThrowableStrRep()[i];
                                            out.println("" +GeneralUtil.htmlEncode(s) + "<br>");
                                        }
                                    
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
} else { 
      out.write("\n");
      out.write("                        ");
      out.print( GeneralUtil.htmlEncode(event.getClass().toString()) );
      out.write(':');
      out.write(' ');
      out.print( GeneralUtil.htmlEncode(event.toString()) );
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
 } catch (Throwable t) { 
      out.write("\n");
      out.write("                <div class=\"error\">\n");
      out.write("                    <div class=\"errorMessage\" style=\"font-weight: bold;\">Error rendering logging information - uh oh.</div>\n");
      out.write("                    <pre>\n");
      out.write("                        ");
 t.printStackTrace(new PrintWriter(out)); 
      out.write("\n");
      out.write("                    </pre>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

    }
    finally
    {
        out.flush();
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
